version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
      # - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      # - '../../etc/ssl:/etc/ssl'
      - './static:/var/www/static' 
      - './media:/media' 
    depends_on:
      - backend 
    networks:
      - dev

  backend: 
    build: . 
    entrypoint: /entrypoint.sh
    ports: 
      - "8000:8000"
      - "5555:5555"
    volumes:
      - './db:/db'
      - ./static:/var/www/static
      - ./media:/media
    networks:
      - dev

networks:
  dev: